name: Run WhatsApp Bot

on:
  workflow_dispatch: # Trigger manually via the GitHub Actions UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Cache Node.js dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Step 4: Install dependencies if not cached
      - name: Install Dependencies
        run: npm install whatsapp-web.js youtube-search-without-api-key youtube-exec fs

      # Step 5: Set environment variables
      - name: Set Environment Variables
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

      # Step 6: Start WhatsApp Bot
      - name: Start WhatsApp Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          node index.js
